---
title: "Schedule"
---

This schedule is a work in progress, so please check it frequently to make sure you know what the next reading is!

```{=html}
<!--
25 class sessions in the semester
[draft syllabus](https://docs.google.com/document/d/1gcTregTaJKTzPuUeHbQEtI3e_38JzYVwixEPD9OOP5c/edit?tab=t.0#heading=h.z4q1b6mv44zf)
-->
```

## Week 2

Week of Sept 14

-   By W2.C1:

    -   (skim) Selections from National Academies of Sciences, Engineering, and Medicine. 2016. Modernizing Crime Statistics: Report 1: Defining and Classifying Crime. Washington, DC: The National Academies Press. <https://www.nationalacademies.org/projects/DBASSE-CNSTAT-13-05> .

    -   Johnson, K. R. (2021). Two Regimes of Prison Data Collection. Harvard Data Science Review, 3(3). <https://doi.org/10.1162/99608f92.72825001>

-   Sign up for a discussion leader and tech skills slots on the [assignments](assignments.qmd#leading-class-discussion) page which has a link to the [Class Leader Schedule](https://docs.google.com/spreadsheets/d/1oqzW3GjvwdGwQpR57L7JWsS9Wvx-1Sehy_xs4PBAoBo/edit?gid=0#gid=0)

-   By W2.C2:

    -   Install everything you need for the [tech stack](tech-stack.qmd). Come to office hours if you're struggling.
    -   Review the information you've received about git in previous classes and come prepared to discuss what git does and why we use it.

## Week 3

Week of Sept 21

-   By W2.C1:

    -   Read Chapters 1 and 2 of *Predict and Surveil*. Bring your book to class.

-   By W2.C2:
    
    -   Have a first draft of research questions ready to discuss
    -   Branch with the start of your project created
    -   Have (or have set a date for) meeting with your research cluster

## Week 4

Week of Sept 28

-   By W4.C1

    -   Read Chapters 3 of *Predict and Surveil*. Bring your book to class.

-   By W4.C2

    -   Stage 1 of research project DUE. This class will be a partly open work session to troubleshoot the submission of this first part of the project.


## Week 5

Week of October 5

-   By W5.C1

    -   Read Chapters 4 & 5 of *Predict and Surveil*. Bring your book to class.
    
-   By W5.C2
    
    - Dataset identified & committed to your branch; 
    - **Four** initial questions asked & answered & committed



## Week 6 - MIDTERM WEEK 

Week of October 12


-   By W6.C1
    -   NO CLASS: Fall Break!
    
-   By W6.C2

    - **Four** more questions asked & answered & committed
    - Initial writing about what you're discovering


Midterm exams will happen between October 14 and 19 and must be in person!  Use [this link](https://calendar.app.google/F31WsHELMJRGvW9z7) to schedule

## Week 7 

Week of October 19

- By W7.C1

    - Read Chapters 6-8 of *Predict and Surveil*. (This is a lot, but it includes the reading for fall break.)

- By W7.C2

    - NO CLASS TODAY (Nikko will be at a conference)
    - Stage 2 deliverable due (PR open, and all tests passing!)

## Week 8 

Week of October 26

- By W8.C1

    - Read Jefferson, Intro and Chapter 1. Bring your book to class.

- By W8.C2

    - first (rough-looking) data visualization idea (we will build a viz in class together)
